language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t danny2327/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true danny2327/docker-react npm run test
